addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"      % "0.11.1")
addCompilerPlugin("org.scalameta" % "semanticdb-scalac" % "4.9.9" cross CrossVersion.full)
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"      % "2.5.2")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"           % "2.1.2")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"      % "3.9.21")
addSbtPlugin("com.github.sbt"     % "sbt-dynver"        % "5.0.1")
